### ISSUE TITLE
Change Request: File system discoverability

### ISSUE THREAD

**Issue by amatiasq** [humanwhocodes/fsx#10]
### Which packages would you like to change?

- [X] `fsx-core`
- [x] `fsx-node`
- [x] `fsx-deno`
- [x] `fsx-memory`
- [x] `fsx-test`
- [x] `fsx-types`

### What problem do you want to solve?

How can we use `fsx` to explore what's already present in the file system?

One use case is a `grep`-like tool. How can we know which files are present in a directory to search through them.
Or a `ls`, how can we print the files and directories contained at a given directory?

We have `isFile()` and `isDirectory()` to detect if they exist but no method to ask `fsx` for the existing files and directories.

### What do you think is the correct solution?

`fsx.list(myDir)` which returns a `Promise<Array<string>>`

### Participation

- [X] I am willing to submit a pull request for this change.

### Additional comments

If the returned strings contain the full path or just the file/directory name is open to discussion.
- Returning the full path will make it easier to follow up with more FS operations. Getting the name requires slicing it.
- Returning the name only will require concatenation to execute another FS operation.

**Comment by MorganConrad** [comment]
I think this is a good idea - I spend about 50% of my node fs code on reading directories.  I agree with @amatiasq  that returning the full path is easier - the concatenation is node fs is a pain.  Also makes it trivial to add a `.filter(fsx.isFile)`.  

I seldom use the dirent option, so returning an array of strings seems fine.

**Comment by nzakas** [comment]
Yes, this is something I've been looking at, just hadn't had the time to document in an issue. I was also thinking the method name should be `list()`. 👍 

The part I'm working through is what the ideal interface for this method would be. If I were doing it from scratch, I would want it to return an async iterator. And in fact, this is how [Deno implements it](https://deno.land/api@v1.39.2?s=Deno.readDir).

However, Node.js implements it by [returning a promise that resolve to an array of strings](https://nodejs.org/api/fs.html#fspromisesreaddirpath-options).

So the question here is which of those two options do I want for this project? I'm slightly leaning towards async iterator, as I think that's the most correct implementation, but definitely interested in opinions.

**Comment by MorganConrad** [comment]
Speaking as a competent but non-superstar programmer, an async iterator may be more correct, but overly sophisticated for many.  Is time or memory is a big issue?  Is there an actual advantage here?

I almost always call `Array.from()` so I don't have to think about them.  :-)

**Comment by amatiasq** [comment]
Deno's implementation feels more correct, `AsyncIterator` leaves the door open for some hypothetical implementation where listing a directory can be made progressively.

On a more pragmatic view I don't see a case where I would use the `AsyncIterator` differently of what I would do with a `Promise` so using `AsyncIterator` would just add noise. After all unless you're using the `AsyncIterator` directly in a `for await (.. of ..)` loop you'll be passing it to `Array.fromAsync()` and get a `Promise<string[]>` back, right?

I'm more inclined to return `Promise<string[]>`.

**Comment by MorganConrad** [comment]
The talk about iterators got me thinking: Will `list()` be recursive?  Perhaps as an option?

 If so, I can see more arguments for them.

**Comment by MichaelMakesGames** [comment]
If there are good use-cases for both an async iterator and a promised array, maybe they could be 2 separate methods?
`fsx.iter` for the iterator, and
`fsx.list` for the promise

**Comment by amatiasq** [comment]
What makes `fsx` great is it's simplicity, this is what makes it so easy to provide new implementations to the abstraction layer.

I'd abstain from adding multiple methods or option parameters to avoid complicating it

**Comment by nzakas** [comment]
> Deno's implementation feels more correct, `AsyncIterator` leaves the door open for some hypothetical implementation where listing a directory can be made progressively.

@amatiasq After thinking about this over the weekend, I think `AsyncIterator` is the best solution for where I want the project to go (compatibility with cloud drives where you'll get batched results).

> The talk about iterators got me thinking: Will `list()` be recursive? Perhaps as an option?
> 
> If so, I can see more arguments for them.

@MorganConrad I see it as not recursive because I believe the recursive case is less common. I'm also not a fan of optional parameters, but I'll see how development goes. The first version will definitely just be listing the current directory's entries.

> If there are good use-cases for both an async iterator and a promised array, maybe they could be 2 separate methods? `fsx.iter` for the iterator, and `fsx.list` for the promise

@MichaelMakesGames there's nothing you can do with a promised array that you can't do with an async iterator. (You can just use `Array.fromAsync()` to create the array you want.) And I'm in agreement with @amatiasq that I want to have one way to do things.

**Comment by nzakas** [comment]
PR is up: https://github.com/humanwhocodes/fsx/pull/25

**Comment by MorganConrad** [comment]
Minor nit, and perhaps wrong.  The `entry` returned by `fsx.list()` has a `.name`, which is consistent with Node.  IMO, it should have a `.path` (or .filePath?) instead.   That makes it more consistent with your use of filePath everywhere else.  And makes it more clear that it is the full path.
