### ISSUE TITLE
Feature Request: handle encodings; document UTF-8 as default in JSDoc

### ISSUE THREAD

**Issue by iliazeus** [humanwhocodes/fsx#13]
### Which packages would you like to change?

- [X] `fsx-core`
- [ ] `fsx-node`
- [ ] `fsx-deno`
- [ ] `fsx-memory`
- [ ] `fsx-test`
- [ ] `fsx-types`

### What problem do you want to solve?

Sad as it may be, UTF-8 is still not the single encoding everywhere.

### What do you think is the correct solution?

Document implicit UTF-8 encoding in JSDoc of every method that uses it. Allow to optionally specify a different encoding.

### Participation

- [ ] I am willing to submit a pull request for this change.

**Comment by nzakas** [comment]
I can definitely update the docs.

I'm not going to add anything for alternate encodings until someone comes to me with a solid use case so I can think through the correct API.
