### ISSUE TITLE
isFile() and isDirectory() should only turn ENOENT to false, not all errors

### ISSUE THREAD

**Issue by iliazeus** [humanwhocodes/fsx#14]
### Which packages would you like to change?

- [ ] `fsx-core`
- [X] `fsx-node`
- [ ] `fsx-deno`
- [ ] `fsx-memory`
- [ ] `fsx-test`
- [ ] `fsx-types`

### What problem do you want to solve?

A "your disk failed" case needs to be handled very differently than a "file not found" one.

### What do you think is the correct solution?

The `.isFile()` and `.isDirectory()` methods should not have a simple `.catch(() => false)`, instead testing the error for `ENOENT`, similar to other methods.

### Participation

- [ ] I am willing to submit a pull request for this change.

**Comment by nzakas** [comment]
Yeah, that's a bug. Thanks for pointing this out.
