### ISSUE TITLE
Bug: missing TS types on released npm package

### ISSUE THREAD

**Issue by Mist3rBru** [humanwhocodes/fsx#31]
### Which packages are affected?

- [X] `fsx-core`
- [X] `fsx-node`
- [ ] `fsx-deno`
- [X] `fsx-memory`
- [ ] `fsx-test`
- [ ] `fsx-types`

### Environment

Node version: v20.10.0
npm version: 10.2.3
Deno version: 
Operating System: Windows, Ubuntu

### What did you do?

I installed the packages on a project in typescript 

### What did you expect to happen?

I expected the types from the packages above to come with it, and show me the `fsx` methods on vscode autocomplete

### What actually happened?

I navigated through the types and noticed that `Fsx` is imported from `fsx-core`, but  `Fsx` type is never imported, because the package does not release the types on `dist/index.d.ts` to npm on release.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/typescript-73emtm?file=index.ts

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by nzakas** [comment]
Ah, interesting. I thought `npm publish` published everything in the directory automatically. TIL.

Definitely want to fix this, but I'd also like to have some way of testing that any change actually fixed the problem.

**Comment by Mist3rBru** [comment]
I don't think there is some way to test it locally, beacause it depends on a third party, but for example, all other packages from this repository has `package.files` included on package.json, and npm has this property described on their documentation.

https://docs.npmjs.com/cli/v10/configuring-npm/package-json#files

**Comment by nzakas** [comment]
Hmm, that is odd. I wonder why only some of the packages have `files` entries. 🤔 

I couldn't find an easy way to test this either, so I'll just make the change. Thanks for the report.
