### ISSUE TITLE
Bug: `fsx-types` does not match `fsx-core` types

### ISSUE THREAD

**Issue by Mist3rBru** [humanwhocodes/fsx#32]
### Which packages are affected?

- [X] `fsx-core`
- [ ] `fsx-node`
- [ ] `fsx-deno`
- [ ] `fsx-memory`
- [ ] `fsx-test`
- [X] `fsx-types`

### Environment

Node version: v20.10.0
npm version: 10.2.3
Deno version:
Operating System: Ubuntu

### What did you do?

I navigated through the types on `fsx-types` , and noticed that the methods of `FsxImpl` are returning only the expected result type, and it is not returning the error type, which would be `undefined`.

### What did you expect to happen?

I expected it return `TResult | undefined`, as mentioned on documentation.
```diff
export interface FsxImpl {
...
	 * @returns The contents of the file or undefined if the file is empty.
-	text?(filePath: string): Promise<string>;
+	text?(filePath: string): Promise<string | undefined>;

     * @returns {Promise<ArrayBuffer|undefined>} The contents of the file as an ArrayBuffer.
-	arrayBuffer?(filePath: string): Promise<ArrayBuffer>;
+	arrayBuffer?(filePath: string): Promise<ArrayBuffer | undefined>;

     * @returns {Promise<Uint8Array|undefined>} The contents of the file as an Uint8Array.
-	bytes?(filePath: string): Promise<Uint8Array>;
+	bytes?(filePath: string): Promise<Uint8Arrayr | undefined>;
...
```

### What actually happened?

It only returns the success result.

### Link to Minimal Reproducible Example

https://github.com/humanwhocodes/fsx/blob/main/packages/types/src/fsx-types.ts

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by nzakas** [comment]
Oops, thanks! I'll get that fixed.
