### ISSUE TITLE
`.bytes()` method appears to not respect TypedArray bounds

### ISSUE THREAD

**Issue by bakkot** [humanwhocodes/fsx#43]
### Which packages are affected?

- [ ] `fsx-core`
- [X] `fsx-node`
- [ ] `fsx-deno`
- [ ] `fsx-memory`
- [ ] `fsx-test`
- [ ] `fsx-types`

### Environment

N/A

### What did you do?

```js
let base = new Uint8Array([5, 6, 7, 8]);
let sub = base.subarray(1, 3);
await fsx.write("file", sub);
```

### What did you expect to happen?

should only write the fours bytes `6` and `7` to "file"

### What actually happened?

writes all four bytes

### Link to Minimal Reproducible Example

N/A

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

I didn't check which packages are affected but it's probably more than just fsx-node. And this isn't published yet so no repro, sorry; this is just from reading the code.

**Comment by nzakas** [comment]
Thanks, that's a nice catch!
