### ISSUE TITLE
`fsx-memory` incorrect constructors types

### ISSUE THREAD

**Issue by Deckluhm** [humanwhocodes/fsx#47]
### Which packages are affected?

- [ ] `fsx-core`
- [ ] `fsx-node`
- [ ] `fsx-deno`
- [X] `fsx-memory`
- [ ] `fsx-test`
- [ ] `fsx-types`

### Environment

Node version: 21.6.1 / Bun 1.0.25
npm version: 10.4.0
Deno version: 1.39.4
Operating System: WSL (Ubuntu 22.04 on Windows 11)

### What did you do?

I wanted to use `fsx-memory` for my unit tests as described on the 2nd example here: https://github.com/humanwhocodes/fsx/blob/main/docs/using-impls.md#swapping-impls-in-practice

```ts
new MemoryFsxImpl() // Expected 1 arguments, but got 0. ts(2554)
```

### What did you expect to happen?

If documentation is correct, I should be able to do `new MemoryFsxImpl()` without TypeScript complaining about missing parameter.

### What actually happened?

TypeScript is complaining about missing parameter.

### Link to Minimal Reproducible Example

https://github.com/Deckluhm/fsx-memory-incorrect-types

### Participation

- [X] I am willing to submit a pull request for this issue.

### Additional comments

If the documentation is correct and `MemoryFsxImpl` parameter is optional, the following changes in https://github.com/humanwhocodes/fsx/blob/main/packages/memory/src/memory-fsx.js will fix it:
```diff
export class MemoryFsxImpl {
  /**
   * The in-memory file system volume to use.
   * @type {object}
   */
  #volume;

  /**
   * Creates a new instance.
-  * @param {object} options The options for the instance.
-  * @param {object} options.volume The in-memory file system volume to use.
+  * @param {object} [options={}] The options for the instance.
+  * @param {object} [options.volume] The in-memory file system volume to use.
   */
- constructor({ volume }) {
+ constructor({ volume } = {}) {
    this.#volume = volume;
  }
}
```
Additionally, `MemoryFsx` constructor should be:
```diff
export class MemoryFsx extends Fsx {
  /**
   * Creates a new instance.
-  * @param {object} options The options for the instance.
+  * @param {object} [options={}] The options for the instance.
   * @param {object} [options.volume] The in-memory file system volume to use.
   */
  constructor({ volume } = {}) {
    super({ impl: new MemoryFsxImpl({ volume }) });
  }
}
```
I couldn't make StackBlitz work with fsx + TypeScript... not sure what happened here 🤷 

I have a PR ready to be submitted if needed.

**Comment by nzakas** [comment]
Thanks for reporting this. It looks like tsc wasn't running in the CI so I didn't catch this. Feel free to submit a PR.

**Comment by nzakas** [comment]
It worked. 🎉 Thanks.
